#!/usr/bin/env python3
"""
ServiceDesk Radar — AI Infrastructure
scripts/evaluate_infrastructure.py  (Step 21)

Offline evaluation runner. Loads config + the embedding model, runs the three
evaluation functions over the full data files, and writes a Markdown report to
docs/evaluation.md (Milestone 5).

This is the only place that performs the startup-style setup for evaluation;
`evaluation.py` itself never loads the model or initializes infrastructure.

Usage:
    python scripts/evaluate_infrastructure.py
        [--config CONFIG] [--eval-set EVAL] [--pairs PAIRS]
        [--old-tickets OLD] [--out docs/evaluation.md]
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from pathlib import Path

# Make `app` importable when this script is run directly from the ai-core root.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.infrastructure import evaluation as ev  # noqa: E402
from app.infrastructure.embedding_model import EmbeddingModel  # noqa: E402

logger = logging.getLogger("evaluate_infrastructure")

_DEFAULT_CONFIG = "config/infrastructure_config.json"
_DEFAULT_EVAL_SET = "data/evaluation_set.json"
_DEFAULT_PAIRS = "data/similarity_pairs.json"
_DEFAULT_OLD_TICKETS = "data/old_tickets.json"
_DEFAULT_OUT = "docs/evaluation.md"

_GAP_TARGET = 0.15


def _load_config(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as fh:
        config = json.load(fh)
    if not isinstance(config, dict):
        raise ValueError(f"{path} must be a JSON object")
    return config


def _render_markdown(sim, sweep, cat, model_version: str) -> str:
    gap_note = " (meets target)" if sim.separation_gap > _GAP_TARGET else " (BELOW 0.15 target)"
    lines: list[str] = [
        "# ServiceDesk Radar — Infrastructure Evaluation",
        "",
        "_Generated by `scripts/evaluate_infrastructure.py`._  ",
        f"Embedding model version: `{model_version}`",
        "",
        "## Similarity Quality",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Total pairs | {sim.total_pairs} |",
        f"| Similar pairs avg score | {sim.similar_pairs_avg_score} |",
        f"| Dissimilar pairs avg score | {sim.dissimilar_pairs_avg_score} |",
        f"| Separation gap (target > {_GAP_TARGET}) | {sim.separation_gap}{gap_note} |",
        f"| Pass rate | {sim.pass_rate} |",
        f"| Recommended threshold | {sim.recommended_threshold} |",
        "",
        "## Threshold Sweep",
        "",
        "| Threshold | Pass rate |",
        "|---|---|",
    ]
    for t, r in zip(sweep.tested_thresholds, sweep.pass_rates):
        lines.append(f"| {t} | {r} |")
    lines += [
        "",
        f"**Recommended threshold:** {sweep.recommended_threshold}",
        "",
        "## Retrieval Category Accuracy",
        "",
        f"Overall: **{cat.correct} / {cat.total_evaluated} = {cat.accuracy}**",
        "",
        "| Category | Accuracy |",
        "|---|---|",
    ]
    for category in sorted(cat.per_category):
        lines.append(f"| {category} | {cat.per_category[category]} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Evaluate infrastructure retrieval quality.")
    parser.add_argument("--config", default=os.environ.get("INFRASTRUCTURE_CONFIG_PATH", _DEFAULT_CONFIG))
    parser.add_argument("--eval-set", default=os.environ.get("EVALUATION_SET_PATH", _DEFAULT_EVAL_SET))
    parser.add_argument("--pairs", default=os.environ.get("SIMILARITY_PAIRS_PATH", _DEFAULT_PAIRS))
    parser.add_argument("--old-tickets", default=os.environ.get("OLD_TICKETS_PATH", _DEFAULT_OLD_TICKETS))
    parser.add_argument("--out", default=_DEFAULT_OUT)
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")

    config = _load_config(args.config)
    emb = config.get("embedding", {})

    model = EmbeddingModel.instance()
    if not model.is_ready:
        logger.info("Loading embedding model '%s' ...", emb.get("model_name"))
        model.load(
            emb.get("model_name"),
            cache_dir=emb.get("cache_dir"),
            model_version=emb.get("model_version"),
        )

    # The eval functions run a mandatory pre-flight that every pair id resolves
    # in the eval set; a stale id raises ValueError before any scoring (M5).
    try:
        sim = ev.eval_similarity_quality(args.eval_set, args.pairs, model, config)
        sweep = ev.eval_threshold_sweep(args.eval_set, args.pairs, model, config)
        cat = ev.eval_retrieval_category_accuracy(args.eval_set, args.old_tickets, model, config)
    except ValueError as exc:
        logger.error("Evaluation pre-flight failed: %s", exc)
        return 1

    model_version = model.model_version or emb.get("model_version", "unknown")
    report = _render_markdown(sim, sweep, cat, model_version)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")

    print(f"Wrote evaluation report -> {out_path}")
    print(
        f"  similarity: gap={sim.separation_gap} pass_rate={sim.pass_rate} "
        f"recommended={sim.recommended_threshold}"
    )
    print(f"  threshold sweep recommended={sweep.recommended_threshold}")
    print(f"  retrieval category accuracy={cat.accuracy} ({cat.correct}/{cat.total_evaluated})")

    if sim.separation_gap <= _GAP_TARGET:
        logger.warning(
            "Separation gap %.4f <= %.2f target. Revise the offending dissimilar "
            "pairs in similarity_pairs.json (do NOT change thresholds to compensate).",
            sim.separation_gap, _GAP_TARGET,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
