INTENT_RULES = {
    "vpn": {
        "vpn_request": [
            "درخواست",
            "درخواست دسترسی",
            "دسترسی جدید",
            "اکانت جدید",
            "ساخت اکانت",
            "فعال سازی",
            "فعال‌سازی",
            "ایجاد",
            "جدید",
            "create",
            "new",
            "account",
            "access request",
        ],
        "vpn_authentication_error": [
            "احراز هویت",
            "کد تایید",
            "کد تأیید",
            "otp",
            "mfa",
            "2fa",
            "توکن",
            "token",
            "authentication",
            "authenticate",
            "auth",
            "ناموفق",
            "تایید نمیشه",
            "تأیید نمیشه",
            "verify",
            "verification",
        ],
        "vpn_connection_issue": [
            "قطع",
            "وصل نمیشه",
            "وصل نمی‌شود",
            "کانکت نمیشه",
            "کانکت نمی‌شود",
            "اتصال برقرار نمیشه",
            "اتصال برقرار نمی‌شود",
            "ارور",
            "خطا",
            "disconnect",
            "disconnected",
            "connectivity",
            "connection",
            "connection failed",
            "cannot connect",
            "error",
            "failed",
        ],
        "vpn_client_issue": [
            "anyconnect",
            "forticlient",
            "openvpn",
            "کلاینت",
            "نرم افزار vpn",
            "نرم‌افزار vpn",
            "آپدیت vpn",
            "بروزرسانی vpn",
            "client",
            "vpn client",
            "update",
            "upgrade",
        ],
    },
    "email": {
        "email_quota_issue": [
            "حجم",
            "فضا",
            "پر شده",
            "صندوق پر",
            "گیگابایت",
            "ظرفیت",
            "quota",
            "full",
            "space",
            "storage",
            "mailbox full",
            "capacity",
        ],
        "email_access_issue": [
            "ورود",
            "لاگین",
            "رمز",
            "پسورد",
            "کلمه عبور",
            "فراموش",
            "قفل",
            "باز نمیشه",
            "باز نمی‌شود",
            "login",
            "sign-in",
            "signin",
            "password",
            "forgot",
            "locked",
            "access",
        ],
        "email_send_receive_issue": [
            "ارسال نمیشه",
            "ارسال نمی‌شود",
            "دریافت نمیشه",
            "دریافت نمی‌شود",
            "دریافت نکرده ام",
            "دریافت نکرده‌ام",
            "ایمیل نمیاد",
            "ایمیل نمی‌رود",
            "گیرنده",
            "فرستنده",
            "send",
            "receive",
            "delivery",
            "undelivered",
            "bounce",
            "smtp",
            "imap",
        ],
        "email_outlook_issue": [
            "outlook",
            "اوتلوک",
            "sync",
            "سینک",
            "همگام سازی",
            "همگام‌سازی",
            "profile",
            "pst",
            "ost",
        ],
    },
    "network": {
        "network_drop": [
            "قطع",
            "وصل",
            "وصل نمیشه",
            "وصل نمی‌شود",
            "اینترنت قطع",
            "وای فای قطع",
            "وای‌فای قطع",
            "کابل",
            "disconnect",
            "disconnected",
            "internet down",
            "wifi down",
            "network down",
            "no internet",
            "internet ندارد",
            "اینترنت ندارد",
            "شبکه ندارد",
            "دسترسی به internet ندارد",
            "دسترسی به اینترنت ندارد",
            "همه کاربران",
            "کل شرکت",
            "کل سازمان",
            "متوقف شده",
            "قطعی کامل",
        ],
        "network_speed": [
            "کندی",
            "خیلی کند",
            "کند شده",
            "کند است",
            "سرعت",
            "پینگ",
            "تاخیر",
            "تأخیر",
            "لگ",
            "slow",
            "speed",
            "ping",
            "latency",
            "lag",
            "timeout",
        ],
        "network_wifi_issue": [
            "وای فای",
            "وای‌فای",
            "wifi",
            "wi-fi",
            "ssid",
            "سیگنال",
            "آنتن",
            "wireless",
            "hotspot",
        ],
        "network_lan_issue": [
            "کابل شبکه",
            "پورت شبکه",
            "lan",
            "ethernet",
            "switch",
            "سوئیچ",
            "آی پی",
            "ip",
            "dhcp",
            "dns",
        ],
    },
    "printer": {
        "printer_error": [
            "خراب",
            "ارور",
            "خطا",
            "گیر",
            "گیر کرده",
            "کاغذ گیر",
            "کاغذ گیر کرده",
            "paper",
            "jam",
            "paper jam",
            "error",
            "fault",
            "offline",
        ],
        "print_queue": [
            "صف",
            "صف چاپ",
            "چاپ نمیشه",
            "چاپ نمی‌شود",
            "پرینت نمیشه",
            "پرینت نمی‌شود",
            "queue",
            "stuck",
            "print queue",
            "pending",
        ],
        "printer_supply_issue": [
            "تونر",
            "کارتریج",
            "جوهر",
            "کم رنگ",
            "کمرنگ",
            "تمام شده",
            "toner",
            "cartridge",
            "ink",
            "low toner",
        ],
        "printer_setup_request": [
            "نصب پرینتر",
            "تعریف پرینتر",
            "اضافه کردن پرینتر",
            "درایور",
            "driver",
            "install printer",
            "add printer",
            "setup printer",
        ],
    },
    "account": {
        "account_lock": [
            "قفل",
            "بسته",
            "لاک",
            "رمز",
            "پسورد",
            "فراموش",
            "ریست",
            "بازنشانی",
            "lock",
            "locked",
            "password",
            "reset",
            "forgot",
            "unlock",
        ],
        "account_creation": [
            "ساخت",
            "ایجاد",
            "تعریف",
            "کاربر جدید",
            "اکانت جدید",
            "حساب جدید",
            "بسازید",
            "ساخته شود",
            "new user",
            "create user",
            "create account",
            "new account",
        ],
        "account_access_issue": [
            "ورود",
            "لاگین",
            "دسترسی ندارم",
            "وارد نمیشه",
            "وارد نمی‌شود",
            "سامانه",
            "پرتال",
            "login",
            "sign-in",
            "access denied",
            "permission denied",
            "portal",
        ],
        "account_deactivation": [
            "غیرفعال",
            "غیر فعال",
            "حذف کاربر",
            "بستن حساب",
            "disable",
            "deactivate",
            "remove user",
            "delete user",
        ],
    },
    "hardware": {
        "hardware_failure": [
            "خراب",
            "سوخته",
            "روشن نمیشه",
            "روشن نمی‌شود",
            "خاموش",
            "مانیتور",
            "کیس",
            "لپ تاپ",
            "لپ‌تاپ",
            "broken",
            "hardware",
            "monitor",
            "power",
            "not turning on",
            "does not turn on",
        ],
        "hardware_request": [
            "درخواست",
            "نیاز دارم",
            "لازم دارم",
            "تجهیزات",
            "قطعه",
            "جدید",
            "request",
            "equipment",
            "device",
            "new hardware",
        ],
        "hardware_peripheral_issue": [
            "موس",
            "ماوس",
            "کیبورد",
            "موس کار نمیکنه",
            "موس کار نمی‌کند",
            "کیبورد کار نمیکنه",
            "کیبورد کار نمی‌کند",
            "وبکم",
            "هدست",
            "اسپیکر",
            "usb",
            "peripheral",
            "webcam",
            "headset",
            "speaker",
        ],
        "hardware_display_issue": [
            "تصویر",
            "صفحه",
            "مانیتور",
            "نمایشگر",
            "پرش تصویر",
            "سیاه",
            "display",
            "screen",
            "no display",
            "black screen",
            "flicker",
        ],
    },
    "software": {
        "software_install": [
            "نصب",
            "دانلود",
            "بروزرسانی",
            "به روزرسانی",
            "آپدیت",
            "install",
            "setup",
            "download",
            "update",
            "upgrade",
        ],
        "software_error": [
            "کرش",
            "خطا",
            "ارور",
            "بسته میشه",
            "بسته می‌شود",
            "اجرا نمیشه",
            "اجرا نمی‌شود",
            "باز نمیشه",
            "باز نمی‌شود",
            "error",
            "crash",
            "close",
            "not opening",
            "failed",
        ],
        "software_license_issue": [
            "لایسنس",
            "مجوز نرم افزار",
            "مجوز نرم‌افزار",
            "فعال سازی",
            "فعال‌سازی",
            "اکتیو",
            "license",
            "activation",
            "activate",
            "expired",
        ],
        "software_access_request": [
            "دسترسی نرم افزار",
            "دسترسی نرم‌افزار",
            "نرم افزار جدید",
            "نرم‌افزار جدید",
            "درخواست نرم افزار",
            "درخواست نرم‌افزار",
            "دسترسی به برنامه",
            "مجوز استفاده از نرم افزار",
            "مجوز استفاده از نرم‌افزار",
            "برنامه crm",
            "software request",
            "software access",
        ],
    },
    "permission": {
        "permission_denied": [
            "خطا",
            "دسترسی ندارم",
            "اجازه ندارم",
            "ندارم",
            "باز نمیشه",
            "باز نمی‌شود",
            "access denied",
            "denied",
            "permission denied",
            "forbidden",
            "unauthorized",
        ],
        "permission_request": [
            "درخواست",
            "مجوز",
            "دسترسی",
            "اشتراک",
            "اشتراکی",
            "اجازه",
            "request",
            "share",
            "allow",
            "grant",
            "access request",
        ],
        "shared_folder_issue": [
            "پوشه",
            "فولدر",
            "فایل",
            "درایو",
            "مسیر شبکه",
            "shared folder",
            "folder",
            "file",
            "drive",
            "network path",
        ],
        "permission_remove_access": [
            "حذف",
            "حذف شود",
            "حذف دسترسی",
            "قطع دسترسی",
            "برداشتن دسترسی",
            "remove access",
            "revoke",
            "disable access",
        ],
    },
}

INTENT_LABELS_FA = {
    "vpn_request": "درخواست دسترسی VPN",
    "vpn_authentication_error": "خطای احراز هویت VPN",
    "vpn_connection_issue": "مشکل اتصال VPN",
    "vpn_client_issue": "مشکل کلاینت VPN",
    "email_quota_issue": "مشکل حجم ایمیل",
    "email_access_issue": "مشکل ورود به ایمیل",
    "email_send_receive_issue": "مشکل ارسال یا دریافت ایمیل",
    "email_outlook_issue": "مشکل Outlook",
    "network_drop": "قطعی شبکه یا اینترنت",
    "network_speed": "کندی شبکه یا اینترنت",
    "network_wifi_issue": "مشکل وای‌فای",
    "network_lan_issue": "مشکل شبکه کابلی",
    "printer_error": "خطای پرینتر",
    "print_queue": "مشکل صف چاپ",
    "printer_supply_issue": "مشکل تونر یا کارتریج",
    "printer_setup_request": "درخواست نصب پرینتر",
    "account_lock": "قفل یا فراموشی رمز حساب",
    "account_creation": "درخواست ایجاد حساب کاربری",
    "account_access_issue": "مشکل دسترسی به حساب یا سامانه",
    "account_deactivation": "درخواست غیرفعال‌سازی حساب",
    "hardware_failure": "خرابی سخت‌افزار",
    "hardware_request": "درخواست تجهیزات سخت‌افزاری",
    "hardware_peripheral_issue": "مشکل تجهیزات جانبی",
    "hardware_display_issue": "مشکل تصویر یا نمایشگر",
    "software_install": "درخواست نصب یا بروزرسانی نرم‌افزار",
    "software_error": "خطای نرم‌افزار",
    "software_license_issue": "مشکل لایسنس نرم‌افزار",
    "software_access_request": "درخواست دسترسی نرم‌افزار",
    "permission_denied": "عدم دسترسی",
    "permission_request": "درخواست مجوز دسترسی",
    "shared_folder_issue": "مشکل فایل یا پوشه اشتراکی",
    "permission_remove_access": "درخواست حذف دسترسی",
}

GENERAL_INTENT_TEMPLATE = "general_{category}_issue"
UNKNOWN_INTENT = "unknown_intent"
