"""create tickets incident table

Revision ID: 0b9a16f92d27
Revises: 2ea5ee8cb76d
Create Date: 2026-09-06 18:16:48.162667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9a16f92d27'
down_revision: Union[str, Sequence[str], None] = '2ea5ee8cb76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets_incident',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('ticket_id', 'incident_id', name='uq_ticket_incident_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets_incident')
    # ### end Alembic commands ###
