"""change [requester] type into integer

Revision ID: 29192162ce32
Revises: 795fcb736a70
Create Date: 2026-10-02 20:40:03.942623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29192162ce32'
down_revision: Union[str, Sequence[str], None] = '795fcb736a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('requester', sa.Integer(), nullable=True))
    op.drop_column('tickets', 'requester_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('requester_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'requester')
    # ### end Alembic commands ###
