"""create ticket similarities table

Revision ID: 2ea5ee8cb76d
Revises: b431675b1bdb
Create Date: 2026-09-06 18:12:18.949737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea5ee8cb76d'
down_revision: Union[str, Sequence[str], None] = 'b431675b1bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similarities_ticket',
    sa.Column('source_ticket_id', sa.Integer(), nullable=False),
    sa.Column('target_ticket_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.CheckConstraint('source_ticket_id <> target_ticket_id', name='ck_similarity_no_self_match'),
    sa.ForeignKeyConstraint(['source_ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('source_ticket_id', 'target_ticket_id', name='uq_similarity_ticket_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarities_ticket')
    # ### end Alembic commands ###
