"""add resolved_at and idempotency_key

Revision ID: 51178de9df31
Revises: 6cfe4f6b4894
Create Date: 2026-09-23 00:00:15.904334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51178de9df31'
down_revision: Union[str, Sequence[str], None] = '6cfe4f6b4894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'alerts',
        sa.Column(
            'idempotency_key',
            sa.String(length=255),
            nullable=False,
        ),
    )

    op.create_unique_constraint(
        'uq_alerts_idempotency_key',
        'alerts',
        ['idempotency_key'],
    )
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'resolved_at')
    op.drop_constraint(
        'uq_alerts_idempotency_key',
        'alerts',
        type_='unique',
    )
    op.drop_column('alerts', 'idempotency_key')
    # ### end Alembic commands ###
