"""create tickets table

Revision ID: 5b1b024547d8
Revises: 
Create Date: 2026-09-06 17:21:19.604457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1b024547d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('requester_name', sa.String(length=100), nullable=True),
    sa.Column('ticket_status', sa.Enum('IN_PROGRESS', 'OPEN', 'RESOLVED', 'CLOSED', name='ticket_status'), nullable=False),
    sa.Column('analysis_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='analysis_status'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
