"""create ticket analysis table

Revision ID: 98dc2f00dbf0
Revises: 5b1b024547d8
Create Date: 2026-09-06 17:42:45.424275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98dc2f00dbf0'
down_revision: Union[str, Sequence[str], None] = '5b1b024547d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('category_label_fa', sa.String(length=150), nullable=True),
    sa.Column('category_score', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(length=150), nullable=True),
    sa.Column('intent_label_fa', sa.String(length=150), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='urgency_status'), nullable=True),
    sa.Column('urgency_score', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(length=100), nullable=True),
    sa.Column('summary_fa', sa.String(), nullable=True),
    sa.Column('suggested_reply_fa', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasons_fa', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('raw_ai_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_index(op.f('ix_ticket_analysis_id'), 'ticket_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_analysis_id'), table_name='ticket_analysis')
    op.drop_table('ticket_analysis')
    # ### end Alembic commands ###
